### ISSUE TITLE
Cannot run setup scripts on Linux

### ISSUE THREAD

**Issue by CIPop** [Azure-Samples/ESP-Samples#10]
To make this work on Linux/Ubuntu, the install path should be either configurable or defaulting to the home folder.
Currently this is defaulting to `/mnt/c/` which isn't working well on anything but WSL.

Workaround:

Edit the install and dev setup scripts and modify /mnt/c to a writable folder.
Also, to understand which serial port to use, check the `dmesg` logs (usually similar to `/dev/ttyUSB0` on Ubuntu 20 LTS).

**Comment by tawalke** [comment]
Hi:

This script is only for WSL.

For Linux there is a link to a script that is provided from Espressif Systems which is noted in the ReadMe.

________________________________

**Comment by CIPop** [comment]
I think that even for WSL, the target could be in user's home. (Not sure if this would work as-is in WSL v2.)

I like these scripts better as they follow the step-by-step guidance. For ESP8266 I didn't find any alternate solution by Espressif.

________________________________

**Comment by tawalke** [comment]
Hi:

For WSL 1 the user home is not accessible outside of WSL/Linux, but in comparison /mnt/c is accessible in both WSL/Linux and Windows.

In WSL 2 that is not the case and we decided that upon that release and update to PnP we would add to the script the option to set desired location.



________________________________

**Comment by tawalke** [comment]
Setup Info for Linux from Expressif System for ESP8266 https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/linux-setup.html

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by CIPop** [comment]
> Setup Info for Linux from Expressif System for ESP8266 https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/linux-setup.html

True but the script is doing all that automatically (and I've tested it to work). It's a lot more convenient. 
Please take issue this as a feature request if it wasn't originally meant to work on Linux.

**Comment by tawalke** [comment]
Hi Cristian:

Which script are you noting? The script for ESP8266 for Linux or for WSL?

The WSL we have covered, but Espressif Systems provides the setup script and info for ESP8266. Here is the install script link from GitHub:
https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/install.sh


________________________________
