### ISSUE TITLE
Needs pip for python2 before running the scripts

### ISSUE THREAD

**Issue by HerraHak** [Azure-Samples/ESP-Samples#12]
Hi,

On my WSL I launched the install script for 8266 but it failed when calling the /usr/bin/python -m pip ... command as I didn't have pip for Python2 installed.

I tried to install it but apparently, pip for python2 isn't available anymore in the ubuntu repository.

This is what helped me overcome the issue : **https://askubuntu.com/questions/1025189/pip-is-not-working-importerror-no-module-named-pip-internal**.

Do you think we can add in the script to verify the presence of pip and then install it if absent?

**Comment by ericmitt** [comment]
Yes, make sense, please do a PR :-)
