### ISSUE TITLE
Can the setup be done thru PowerShell?

### ISSUE THREAD

**Issue by Ayanmullick** [Azure-Samples/ESP-Samples#3]
@ericmitt, @drajput, @tawalke, thanks for the [demo video](https://www.youtube.com/watch?v=nwxkUQPESCU). I wanted to know if this setup could be achieved with the respective PowerShell modules for Azure and IoT.

**Comment by tawalke** [comment]
Hi @Ayanmullick, the setup for Azure can be done via Powershell, but the ESP-IDF v.3.0 framework from Espressif based upon the documentation can be installed on Windows via MinGW or CMD using their scripts. 
However, if you want to use the latest version of the ESP-IDF v4.x (lates), they do have a Powershell script for installation: https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup-update.html
 
I should note the components we have provided here have been tested using the stable (v3.0 production) but should work with v4.x as well.

**Comment by Ayanmullick** [comment]
Thanks @tawalke, for the update. The [link ](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup-update.html) just asks to use a batch script from the Powershell console. 

Is there an Azure Sample that documents the PowerShell steps to achieve this using the  [PowerShell-IoT module](https://github.com/PowerShell/PowerShell-IoT) ?  like below

<details>

<a href="https://www.youtube.com/embed/jOT_yvlbXI4?start=761&end=813
" target="_blank"><img src="http://img.youtube.com/vi/jOT_yvlbXI4/0.jpg"
alt="IMAGE ALT TEXT HERE" width="180" height="120" border="10" /></a>

**Comment by tawalke** [comment]
Oh sorry @Ayanmullick  thanks for the clarification. No sorry there is not a Azure Sample for Espressif devices using Powershell-IoT module.

**Comment by ericmitt** [comment]
@Ayanmullick do you need more on this issue, or can we close it ?

**Comment by Ayanmullick** [comment]
@ericmitt , In December's Community Call the PowerShell team had discussed about a stripped down version of PowerShell that could potentially run on microcontrollers. The PowerShell team is probably busy with the version 7 release. But I would be interested to confirm if it's possible to have a pure-PowerShell Azure Sample to connect IoT [ESP] to Azure

**Comment by tawalke** [comment]
Hi @Ayanmullick Currently there is not a version of Powershell that can run on a microcontroller or FreeRTOS (which ESP32/8266 runs). //cc @ericmitt

**Comment by Ayanmullick** [comment]
@tawalke @ericmitt , Could the issue be reopened once the PowerShell micro-controller version is available? We can close this temporarily.

**Comment by ericmitt** [comment]
@Ayanmullick make sense, closing for now.
