### ISSUE TITLE
Feather Huzzah esp-8266?

### ISSUE THREAD

**Issue by creationsoft** [Azure-Samples/ESP-Samples#4]
Hi, I've tried this against my device above and get the following errors.
I'm guessing it's because there aren't any buttons (other than reset) on this device.
Any guidance of what I'd need to tweak in the code to get this to work please? e.g. remove the reference to the button somehow?
Thanks!

/mnt/c/esp-samples/samples/azure-esp-starter/components/button/button/button.c: In function 'button_gpio_isr_handler':
/mnt/c/esp-samples/samples/azure-esp-starter/components/button/button/button.c:235:9: error: implicit declaration of function 'portYIELD_FROM_ISR' [-Werror=implicit-function-declaration]
         portYIELD_FROM_ISR();
         ^
/mnt/c/esp-samples/samples/azure-esp-starter/components/button/button/button.c: At top level:
cc1: warning: unrecognized command line option '-Wno-frame-address'
cc1: some warnings being treated as errors
/mnt/c/azure-iot/esp/8266/ESP8266_RTOS_SDK/make/component_wrapper.mk:291: recipe for target 'button/button.o' failed
make[1]: *** [button/button.o] Error 1
/mnt/c/azure-iot/esp/8266/ESP8266_RTOS_SDK/make/project.mk:571: recipe for target 'component-button-build' failed
make: *** [component-button-build] Error 2

**Comment by ericmitt** [comment]
Hi Creationsoft, sorry for the delay. You should remove the button folder under the component folder, and remove reference to it in the code.
If you start from the azure-esp8266-posturesensor project, it should be easier (this project doesn't use button)
Hope this help

**Comment by ericmitt** [comment]
Closing for now.  @Creationsoft Let us know if it is solved for you
