### ISSUE TITLE
Question: ESP32-S2 Examples

### ISSUE THREAD

**Issue by askpatrickw** [Azure-Samples/ESP-Samples#8]
Are there any known issues with these samples on the ESP32-S2 and the latest IDF versions?

**Comment by ericmitt** [comment]
Not tested on our side. If you test that @askpatrickw  interested by the feedback!

**Comment by tawalke** [comment]
@askpatrickw Are you seeing challenges with the latest IDF versions?

**Comment by askpatrickw** [comment]
I did not test them. Didn't need them in our project.
